version: "3.9"
services:
  my_sql_db: 
    image: mysql:latest
    container_name: DB
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: "user"
      MYSQL_DATABASE: 'book_store'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - my-network

  fastapi:
    image: backend:latest
    container_name: fast_api
    ports:
      - "8080:8080"
    depends_on:
      - my_sql_db
    networks:
      - my-network
    links:
      - "my_sql_db"

  reactjs:
    image: react-app:latest
    container_name: react_js
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    networks:
      - my-network
    links:
      - "fastapi"

networks:
  my-network:
    driver: bridge

    
    
  
